env:
  global:
  - CC_TEST_REPORTER_ID=e17faddf12fdbb8b945618efb6e91b742e5a0a12b2c6077d87232f596f5b0026
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
services:
  - postgresql
before_script:
- npm install
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- psql -c \i src/db/buildDB.sql -U postgres
script:
script:
- npm test
- npm run coveralls
- npm run codeClimate
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
